query getProductsOfCategory($categoryTree: String, $from: Int!, $to: Int!) {
  getProductsOfCategory(categoryTree: $categoryTree, from: $from, to: $to) {
    status
    data {
      productId
      productName
      brand
      categoryId
      pricePerUnit
      leyDeGondolas
      linkText
      items {
        itemId
        name
        images {
          imageId
          imageUrl
          imageText
        }
      }
    }
  }
}
