query getPaginationData($page: Int!, $pageSize: Int!) {
  products(pageSize: $pageSize, page: $page, term: "", filters: {categoryId: "63"})
    @context(provider: "vtex.catalog-graphql") {
    paging{
      page
      perPage
      total
      pages
    }
  }
}
